# Plan and apply on pull requests
name: CI

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version_file: .opentofu-version
      - run: tofu fmt -recursive -check

  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: prepare
        uses: gmo-media/tofu-actions/prepare@v1
    outputs:
      strategy: ${{ steps.prepare.outputs.strategy }}
      merged-pr-run-id: ${{ steps.prepare.outputs.merged-pr-run-id }}

  plan:
    needs: [ prepare ]
    name: Plan (${{ matrix.dir }})
    if: ${{ github.event_name == 'pull_request' && needs.prepare.outputs.strategy != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.prepare.outputs.strategy) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version_file: .opentofu-version
      - uses: gmo-media/tofu-actions/setup-aws-credentials@v1
        with:
          aws_credentials: ${{ secrets.AWS_CREDENTIALS }}
      - uses: gmo-media/tofu-actions/plan@v1
        with:
          dir: ${{ matrix.dir }}

  plan-comment:
    needs: [ prepare, plan ]
    if: ${{ always() }}
    name: Plan comment
    runs-on: ubuntu-latest
    steps:
      - uses: gmo-media/tofu-actions/plan-comment@v1

  apply:
    needs: [ prepare ]
    name: Apply (${{ matrix.dir }})
    if: ${{ github.event_name == 'push' && needs.prepare.outputs.strategy != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.prepare.outputs.strategy) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version_file: .opentofu-version
      - uses: gmo-media/tofu-actions/setup-aws-credentials@v1
        with:
          aws_credentials: ${{ secrets.AWS_CREDENTIALS }}
      - uses: gmo-media/tofu-actions/apply@v1
        with:
          dir: ${{ matrix.dir }}
          run-id: ${{ needs.prepare.outputs.merged-pr-run-id }}
