# Drift checkを行う
name: Drift Check

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 0 * * *"

jobs:
  drift-check:
    strategy:
      fail-fast: false
      matrix:
        dir:
          - dev
          - prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ env.TOFU_VERSION }}
      - uses: gmo-media/tofu-actions/setup-aws-credentials@v1
        with:
          aws_credentials: ${{ secrets.AWS_CREDENTIALS }}
      - id: plan
        uses: gmo-media/tofu-actions/plan@v1
        with:
          dir: ${{ matrix.dir }}
      - uses: gmo-media/tofu-actions/notify-drift@v1
        with:
          dir: ${{ matrix.dir }}
          plan: ${{ steps.plan.outputs.plan }}
          webhook: "https://hooks.slack.com/services/..."
