# Run drift checks manually or on cron
name: Drift Check

on:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: "0 0 * * *"

env:
  AWS_REGION: ap-northeast-1
  TOFU_VERSION: 1.10.5

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: prepare
        uses: gmo-media/tofu-actions/prepare@v1
        with:
          force-all-changed: 'true'
    outputs:
      strategy: ${{ steps.prepare.outputs.strategy }}

  drift-check:
    needs: [ prepare ]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.prepare.outputs.strategy) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ env.TOFU_VERSION }}
      - uses: gmo-media/tofu-actions/setup-aws-credentials@v1
        with:
          aws_credentials: ${{ secrets.AWS_CREDENTIALS }}
      - id: plan
        uses: gmo-media/tofu-actions/plan@v1
        with:
          dir: ${{ matrix.dir }}
      - if: ${{ steps.plan.outputs.has-diff == 'true' }}
        uses: gmo-media/tofu-actions/notify-drift@v1
        with:
          dir: ${{ matrix.dir }}
          plan: ${{ steps.plan.outputs.plan }}
          webhook: "https://hooks.slack.com/services/..."
