# Plan manually
name: Plan
run-name: Plan (${{ inputs.dir }})

on:
  workflow_dispatch:
    inputs:
      dir:
        description: Directory to run in
        type: choice
        required: true
        default: dev
        options:
          - dev
          - prod

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version_file: .opentofu-version
      - uses: gmo-media/tofu-actions/setup-aws-credentials@v1
        with:
          aws_credentials: ${{ secrets.AWS_CREDENTIALS }}
      - uses: gmo-media/tofu-actions/plan@v1
        with:
          dir: ${{ inputs.dir }}
