name: Plan comment

inputs:
  apply_workflow_id:
    description: Workflow ID (filename) to apply plans
    default: apply.yaml

runs:
  using: composite
  steps:
    - name: Download plan texts
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
      with:
        pattern: plan-text-*
        path: /tmp/
        merge-multiple: true

    - id: composite
      name: Composite plan texts
      shell: bash
      run: |
        echo "## Plan" > /tmp/comment.txt

        if ls -d -- /tmp/plan-*.txt >/dev/null 2>&1; then
          found=true
        else
          found=false
        fi

        if [ "$found" = true ]; then
          echo 'These plan(s) will be applied automatically upon merging this PR.' >> /tmp/comment.txt
          echo '' >> /tmp/comment.txt
          echo 'To manually apply these plan(s), visit' >> /tmp/comment.txt
          echo '${{ github.server_url }}/${{ github.repository }}/actions/workflows/${{ inputs.apply_workflow_id }}' >> /tmp/comment.txt
          echo 'and fill `${{ github.run_id }}` to run_id parameter.' >> /tmp/comment.txt
        fi

        while IFS= read -r -d '' file; do
          dir_name="${file#/tmp/plan-}"
          dir_name="${dir_name%.txt}"
          dir_name="${dir_name//___/\/}"

          echo "### $dir_name" >> /tmp/comment.txt
          echo '```' >> /tmp/comment.txt
          cat $file >> /tmp/comment.txt
          echo '```' >> /tmp/comment.txt
        done < <(find /tmp -name 'plan-*.txt' -print0)

        if [ "$found" = false ]; then
          echo 'No plan output found. If plans are failing, check their logs.' >> /tmp/comment.txt
        fi

        echo 'comment<<EOF' >> $GITHUB_OUTPUT
        cat /tmp/comment.txt >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT
        LENGTH=$(wc -c /tmp/comment.txt | awk '{print $1}')
        echo "length=$LENGTH" >> $GITHUB_OUTPUT

    - if: ${{ steps.composite.outputs.length > 50000 }}
      name: Add comment
      uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
      with:
        message-id: plan-${{ github.event.pull_request.number }}
        message-failure: Plan was not successful
        message: |
          ## Plan
          Plan result was too long (> 50k chars) to include in PR comment.
          Please check actions summary for more info.
          ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          
          To manually apply these plan(s), visit
          ${{ github.server_url }}/${{ github.repository }}/actions/workflows/${{ inputs.apply_workflow_id }}
          and fill `${{ github.run_id }}` to run_id parameter.

    - if: ${{ steps.composite.outputs.length <= 50000 }}
      name: Add comment
      uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
      with:
        message-id: plan-${{ github.event.pull_request.number }}
        message-failure: Plan was not successful
        message: ${{ steps.composite.outputs.comment }}
