name: Plan
description: Run tofu/terraform plan and parse results

inputs:
  config:
    description: tofu-actions config file
    default: .github/tofu-actions-config.js
  dir:
    description: Directory to run in
    required: true
  apply_workflow_id:
    description: Workflow ID (filename) to apply plans
    default: apply.yaml

outputs:
  plan:
    description: Plan string
    value: ${{ steps.plan.outputs.plan }}
  has-diff:
    description: Plan has diff
    value: ${{ steps.plan.outputs.has-diff }}
  import-count:
    description: Number of resources to import
    value: ${{ steps.parse-plan.outputs.import }}
  add-count:
    description: Number of resources to add
    value: ${{ steps.parse-plan.outputs.add }}
  change-count:
    description: Number of resources to change
    value: ${{ steps.parse-plan.outputs.change }}
  destroy-count:
    description: Number of resources to destroy
    value: ${{ steps.parse-plan.outputs.destroy }}
  replace-count:
    description: Number of resources to replace
    value: ${{ steps.parse-plan.outputs.replace }}
  forget-count:
    description: Number of resources to forget
    value: ${{ steps.parse-plan.outputs.forget }}

runs:
  using: composite
  steps:
    - id: config
      uses: gmo-media/tofu-actions/read-config@v5
      with:
        config: ${{ inputs.config }}
        dir: ${{ inputs.dir }}

    - name: Sanitize artifact name
      id: artifact-name
      shell: bash
      run: |
        DIR="${{ inputs.dir }}"
        NAME="${DIR//\//___}"
        echo "name=$NAME" >> $GITHUB_OUTPUT

    - id: plan
      name: Plan
      working-directory: ${{ inputs.dir }}
      shell: bash
      run: |
        set -o pipefail

        set +o pipefail
        ${{ steps.config.outputs.tf-binary }} plan -lock-timeout=300s ${{ contains(steps.config.outputs.tf-binary, 'tofu') && '-concise ' || ''}}-detailed-exitcode -out /tmp/tf.plan | tee /tmp/plan-raw.txt
        PLAN_EXIT_CODE=${PIPESTATUS[0]}
        set -o pipefail
        # Exit code 1 means execution error, so fail the step
        if [ $PLAN_EXIT_CODE -eq 1 ]; then
          exit 1
        fi

        # Remove ansi colors
        </tmp/plan-raw.txt sed -e 's/\x1b\[[0-9;]*m//g' \
          | grep -v -E "Refreshing state|will perform the following actions" \
          | grep -v -E "used the selected providers to generate the following execution|Resource actions are indicated with the following symbols" \
          | grep -v -E "Acquiring state lock|Reading|Still reading|Read complete after" \
          | grep -v -E "has compared your real infrastructure against your configuration and|found no differences, so no changes are needed|Releasing state lock" \
          | grep -v -E "─────────────────────────────────────────────────────────────────────────────" \
          | grep -v -E "Saved the plan to|To perform exactly these actions, run the following command to apply|${{ inputs.tf-binary }} apply \"/tmp/tf.plan\"" \
          > /tmp/plan.txt
        cp /tmp/plan.txt /tmp/plan-${{ steps.artifact-name.outputs.name }}.txt

        echo 'plan<<EOF' >> $GITHUB_OUTPUT
        cat /tmp/plan.txt >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

        echo '### Plan (${{ inputs.dir }})' >> $GITHUB_STEP_SUMMARY
        echo '```plaintext' >> $GITHUB_STEP_SUMMARY
        cat /tmp/plan.txt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo 'To manually apply this plan, visit' >> $GITHUB_STEP_SUMMARY
        echo '${{ github.server_url }}/${{ github.repository }}/actions/workflows/${{ inputs.apply_workflow_id }}' >> $GITHUB_STEP_SUMMARY
        echo 'and fill `${{ github.run_id }}` to run_id parameter.' >> $GITHUB_STEP_SUMMARY

        if [ $PLAN_EXIT_CODE -eq 0 ]; then
          echo "has-diff=false" >> $GITHUB_OUTPUT
        elif [ $PLAN_EXIT_CODE -eq 2 ]; then
          echo "has-diff=true" >> $GITHUB_OUTPUT
        else
          echo "Unexpected exit code: $PLAN_EXIT_CODE"
          exit 1
        fi

    - id: parse-plan
      name: Parse plan JSON
      working-directory: ${{ inputs.dir }}
      shell: bash
      run: |
        # Get plan in JSON format
        ${{ steps.config.outputs.tf-binary }} show -json /tmp/tf.plan > /tmp/plan.json

        # Parse resource_changes to count each action type in a single jq call
        # Actions: create, update, delete, replace (delete+create or create+delete), forget
        # Import is indicated by "importing" property in the change object
        eval "$(jq -r '
          .resource_changes // [] |
          {
            import: [.[] | select(.change.importing != null)] | length,
            add: [.[] | select(.change.actions == ["create"] and .change.importing == null)] | length,
            change: [.[] | select(.change.actions == ["update"])] | length,
            destroy: [.[] | select(.change.actions == ["delete"])] | length,
            replace: [.[] | select((.change.actions == ["delete", "create"]) or (.change.actions == ["create", "delete"]))] | length,
            forget: [.[] | select(.change.actions == ["forget"])] | length
          } |
          "IMPORT_COUNT=\(.import)\nADD_COUNT=\(.add)\nCHANGE_COUNT=\(.change)\nDESTROY_COUNT=\(.destroy)\nREPLACE_COUNT=\(.replace)\nFORGET_COUNT=\(.forget)"
        ' /tmp/plan.json)"

        echo "import=$IMPORT_COUNT" >> $GITHUB_OUTPUT
        echo "add=$ADD_COUNT" >> $GITHUB_OUTPUT
        echo "change=$CHANGE_COUNT" >> $GITHUB_OUTPUT
        echo "destroy=$DESTROY_COUNT" >> $GITHUB_OUTPUT
        echo "replace=$REPLACE_COUNT" >> $GITHUB_OUTPUT
        echo "forget=$FORGET_COUNT" >> $GITHUB_OUTPUT

        echo "### Plan Summary (${{ inputs.dir }})" >> $GITHUB_STEP_SUMMARY
        echo "| Action | Count |" >> $GITHUB_STEP_SUMMARY
        echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
        echo "| Import | $IMPORT_COUNT |" >> $GITHUB_STEP_SUMMARY
        echo "| Add | $ADD_COUNT |" >> $GITHUB_STEP_SUMMARY
        echo "| Change | $CHANGE_COUNT |" >> $GITHUB_STEP_SUMMARY
        echo "| Destroy | $DESTROY_COUNT |" >> $GITHUB_STEP_SUMMARY
        echo "| Replace | $REPLACE_COUNT |" >> $GITHUB_STEP_SUMMARY
        echo "| Forget | $FORGET_COUNT |" >> $GITHUB_STEP_SUMMARY

        # Save counts to file for aggregation in plan-comment
        cat > /tmp/plan-counts-${{ steps.artifact-name.outputs.name }}.json <<PLAN_COUNTS_EOF
        {"dir": "${{ inputs.dir }}", "import": $IMPORT_COUNT, "add": $ADD_COUNT, "change": $CHANGE_COUNT, "destroy": $DESTROY_COUNT, "replace": $REPLACE_COUNT, "forget": $FORGET_COUNT}
        PLAN_COUNTS_EOF

    - name: Upload plan counts
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: plan-counts-${{ steps.artifact-name.outputs.name }}
        path: /tmp/plan-counts-${{ steps.artifact-name.outputs.name }}.json

    - name: Upload plan text
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: plan-text-${{ steps.artifact-name.outputs.name }}
        path: /tmp/plan-${{ steps.artifact-name.outputs.name }}.txt
    - name: Upload plan file
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      with:
        name: plan-file-${{ steps.artifact-name.outputs.name }}
        path: /tmp/tf.plan
