name: Apply

inputs:
  config:
    description: tofu-actions config file
    default: .github/tofu-actions-config.js
  dir:
    description: Directory to run in
    required: true
  run-id:
    description: Actions run ID where plan was generated
    required: true

runs:
  using: composite
  steps:
    - id: config
      uses: gmo-media/tofu-actions/read-config@v5
      with:
        config: ${{ inputs.config }}
        dir: ${{ inputs.dir }}

    - name: Sanitize artifact name
      id: artifact-name
      shell: bash
      run: |
        DIR="${{ inputs.dir }}"
        NAME="${DIR//\//___}"
        echo "name=$NAME" >> $GITHUB_OUTPUT
    - name: Download plan
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
      with:
        github-token: ${{ github.token }}
        run-id: ${{ inputs.run-id }}
        name: plan-file-${{ steps.artifact-name.outputs.name }}
        path: /tmp/

    - name: Apply
      working-directory: ${{ inputs.dir }}
      shell: bash
      run: ${{ steps.config.outputs.tf-binary }} apply -lock-timeout=300s /tmp/tf.plan
