#!/usr/bin/env bash
# Create the drift-fix pull request, or update the existing one when the
# guard re-ran the fix on its branch (MODE=update). Unverified fixes
# (VERDICT=draft-pr) become/stay a draft PR with a warning so a human can
# finish the fix; the idempotency guard still sees the open PR and keeps
# later cron runs from re-running Claude while the PR stays valid.
#
# Env:    GH_TOKEN, DIR, TF_BINARY, BASE_BRANCH, BRANCH_NAME, VERDICT,
#         MODE, EXISTING_PR_NUMBER (only when MODE=update),
#         VERIFY_PLAN_TXT (set by verify-drift-resolved.sh via GITHUB_ENV)
# Reads:  "$VERIFY_PLAN_TXT" (written by verify-drift-resolved.sh)
# Writes: pr-url / summary to GITHUB_OUTPUT
set -euo pipefail

: "${DIR:?DIR is required}"
: "${TF_BINARY:?TF_BINARY is required}"
: "${BASE_BRANCH:?BASE_BRANCH is required}"
: "${BRANCH_NAME:?BRANCH_NAME is required}"
: "${VERDICT:?VERDICT is required}"
: "${MODE:?MODE is required}"
: "${GH_TOKEN:?GH_TOKEN is required}"
: "${VERIFY_PLAN_TXT:?VERIFY_PLAN_TXT is required (set by verify-drift-resolved.sh via GITHUB_ENV)}"

# Check if changes were pushed. In update mode the PR branch always exists
# on origin, so this never triggers there; pushes are guaranteed by the
# verdict gate (pr / draft-pr implies a working-tree diff was committed).
if ! git rev-parse --verify "origin/$BRANCH_NAME" >/dev/null 2>&1; then
  echo "No changes were pushed, skipping PR creation"
  exit 0
fi

BODY_FILE=/tmp/pr-body.md
: > "$BODY_FILE"
DRAFT_FLAG=()

if [ "$VERDICT" = "draft-pr" ]; then
  TITLE="⚠️ Auto-fix infrastructure drift in $DIR (unverified)"
  DRAFT_FLAG=(--draft)
  VERIFIED_LINE="- ⚠️ NOT verified: \`$TF_BINARY plan\` still shows changes (see above)"
  {
    echo "## ⚠️ Verification failed"
    echo
    echo "After the automated fix, \`$TF_BINARY plan\` still shows changes."
    echo "A human needs to finish this fix before merging."
    echo "Remaining plan output (truncated to 40000 characters; the full output is in the workflow job summary):"
    echo
    # Indented code block: unlike a ``` fence, plan output that
    # itself contains backticks cannot break out and render as
    # markdown -- but only while EVERY emitted line stays indented.
    # head -c cuts on a byte boundary, so it can leave a final partial
    # line with no trailing newline; awk treats that fragment as a
    # record and print appends a newline, so the last line is still
    # indented and terminated (sed would leave it unterminated).
    head -c 40000 "$VERIFY_PLAN_TXT" | awk '{ print "    " $0 }'
    echo
    echo
  } >> "$BODY_FILE"
else
  TITLE="🔧 Auto-fix infrastructure drift in $DIR"
  VERIFIED_LINE="- Verified: \`$TF_BINARY plan\` shows \"No changes\" after the fix"
fi

cat >> "$BODY_FILE" <<EOF
## 🤖 Automated Drift Fix

This PR is an automatic attempt to fix infrastructure drift in \`$DIR\`.

### What happened?
Infrastructure drift was detected during the drift check. This means the real-world infrastructure
state differs from what's defined in the Terraform/OpenTofu configuration files.

### What this PR does
- Updates the .tf configuration files to match the current real infrastructure state
- Makes minimal, non-destructive changes
$VERIFIED_LINE

### Review checklist
- [ ] Review the changes to ensure they correctly reflect the infrastructure state
- [ ] Verify that only drifted values were updated
- [ ] Confirm no unnecessary default values were added
- [ ] Check that the changes are minimal and non-destructive

---
*This PR was automatically generated by the drift fix workflow using Claude Code.*
EOF

if [ "$MODE" = "update" ]; then
  : "${EXISTING_PR_NUMBER:?EXISTING_PR_NUMBER is required when MODE=update}"

  # Sync the PR's look to the latest verification result: title, body and
  # draft/ready state always reflect the current verdict.
  gh pr edit "$EXISTING_PR_NUMBER" --title "$TITLE" --body-file "$BODY_FILE"

  IS_DRAFT=$(gh pr view "$EXISTING_PR_NUMBER" --json isDraft -q .isDraft)
  if [ "$VERDICT" = "pr" ] && [ "$IS_DRAFT" = "true" ]; then
    gh pr ready "$EXISTING_PR_NUMBER"
  elif [ "$VERDICT" = "draft-pr" ] && [ "$IS_DRAFT" = "false" ]; then
    gh pr ready --undo "$EXISTING_PR_NUMBER"
  fi

  if [ "$VERDICT" = "pr" ]; then
    RESULT_LINE="The fix is now verified: \`$TF_BINARY plan\` shows \"No changes\"."
  else
    RESULT_LINE="The fix is still unverified: \`$TF_BINARY plan\` shows remaining changes (see the PR description)."
  fi
  gh pr comment "$EXISTING_PR_NUMBER" --body "🤖 New drift was detected in \`$DIR\` since the last automated fix on this branch (the infrastructure changed again), so the automated fix was re-run. $RESULT_LINE"

  PR_URL=$(gh pr view "$EXISTING_PR_NUMBER" --json url -q .url)
  echo "Pull request updated: $PR_URL"
else
  PR_URL=$(gh pr create \
      --title "$TITLE" \
      --base "$BASE_BRANCH" \
      --head "$BRANCH_NAME" \
      --body-file "$BODY_FILE" \
      "${DRAFT_FLAG[@]}")

  echo "Pull request created: $PR_URL"
fi
echo "pr-url=$PR_URL" >> "$GITHUB_OUTPUT"
if [ "$VERDICT" = "draft-pr" ]; then
  echo "summary=Claude opened a draft drift-fix PR for \`$DIR\` (verification failed — needs a human): $PR_URL" >> "$GITHUB_OUTPUT"
else
  echo "summary=Claude opened a verified drift-fix PR for \`$DIR\`: $PR_URL" >> "$GITHUB_OUTPUT"
fi
