# Plan and apply on pull requests
name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read
  actions: read
  pull-requests: write
  id-token: write

jobs:
  ci:
    uses: gmo-media/tofu-actions/.github/workflows/quickstart-ci.yaml@v4
    with:
      aws-plan-role: arn:aws:iam::0123456789:role/my-plan-role-name
      aws-apply-role: arn:aws:iam::0123456789:role/my-apply-role-name
