# Plan manually
name: Plan
run-name: Plan (${{ inputs.dir }})

on:
  workflow_dispatch:
    inputs:
      dir:
        description: Directory to run in
        type: choice
        required: true
        default: dev
        options:
          - dev
          - prod

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    uses: gmo-media/tofu-actions/.github/workflows/quickstart-plan.yaml@v4
    with:
      aws-role: arn:aws:iam::0123456789:role/my-plan-role-name
      dir: ${{ inputs.dir }}
