# Plan manually
name: Plan
run-name: Plan (${{ inputs.dir }})

on:
  workflow_call:
    inputs:
      tf-binary:
        description: Terraform or OpenTofu binary name
        type: string
        default: tofu
      terraform-version:
        description: Terraform version to use (if tf-binary is terraform)
        type: string
        default: latest

      auth-mode:
        description: >-
          Authentication mode.
          Activate multiple modes by separating them with spaces.
          Possible values: aws-oidc (default), aws-cred (deprecated), gcp-oidc
        type: string
        default: aws-oidc
      aws-region:
        description: AWS region (required when auth-mode contains aws-oidc)
        type: string
        default: ap-northeast-1
      aws-role:
        description: >-
          AWS role to assume (required when auth-mode contains aws-oidc)
          e.g. arn:aws:iam::0123456789:role/my-plan-role-name
        type: string
      gcp-project:
        description: GCP project ID (required when auth-mode contains gcp-oidc)
        type: string
      gcp-idp:
        description: >-
          GCP workload identity provider (required when auth-mode contains gcp-oidc)
          e.g. projects/0123456789/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider
        type: string

      dir:
        description: Directory to run in
        type: string
        required: true

    secrets:
      aws-cred:
        description: AWS credentials (required when auth-mode contains aws-cred)
        required: false

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: gmo-media/tofu-actions/configure@v4
        with:
          tf-binary: ${{ inputs.tf-binary }}
          terraform-version: ${{ inputs.terraform-version }}
          dir: ${{ inputs.dir }}
          auth-mode: ${{ inputs.auth-mode }}
          aws-region: ${{ inputs.aws-region }}
          aws-role: ${{ inputs.aws-role }}
          aws-cred: ${{ secrets.aws-cred }}
          gcp-project: ${{ inputs.gcp-project }}
          gcp-idp: ${{ inputs.gcp-idp }}

      - uses: gmo-media/tofu-actions/plan@v4
        with:
          tf-binary: ${{ inputs.tf-binary }}
          dir: ${{ inputs.dir }}
