# Apply manually
name: Apply
run-name: Apply (${{ inputs.dir }})

on:
  workflow_call:
    inputs:
      dir:
        description: Directory to run in
        type: string
        required: false
      run-id:
        description: Actions run ID where plan was generated
        type: string
        required: true

permissions:
  contents: read
  actions: read
  id-token: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: gmo-media/tofu-actions/configure@v5
        with:
          dir: ${{ inputs.dir }}
          mode: apply

      - uses: gmo-media/tofu-actions/apply@v5
        with:
          dir: ${{ inputs.dir }}
          run-id: ${{ inputs.run-id }}
