# Plan manually
name: Plan
run-name: Plan (${{ inputs.dir }})

on:
  workflow_call:
    inputs:
      dir:
        description: Directory to run in
        type: string
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: gmo-media/tofu-actions/configure@v5
        with:
          dir: ${{ inputs.dir }}

      - uses: gmo-media/tofu-actions/plan@v5
        with:
          tf-binary: ${{ inputs.tf-binary }}
          dir: ${{ inputs.dir }}
