# Plan manually
name: Plan
run-name: Plan (${{ inputs.dir }})

on:
  workflow_call:
    inputs:
      auth-mode:
        description: Authentication mode (aws-oidc or aws-cred, aws-cred is deprecated)
        type: string
        default: aws-oidc
      aws-region:
        description: AWS region (required when auth-mode is aws-oidc)
        type: string
        default: ap-northeast-1
      aws-role:
        description: >-
          AWS role to assume (required when auth-mode is aws-oidc)
          e.g. arn:aws:iam::0123456789:role/my-plan-role-name
        type: string

      dir:
        description: Directory to run in
        type: string
        required: true

    secrets:
      aws-cred:
        description: AWS credentials (required when auth-mode is aws-cred)
        required: false

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ inputs.auth-mode == 'aws-cred' }}
        uses: gmo-media/tofu-actions/setup-aws-credentials@v2
        with:
          aws_credentials: ${{ secrets.aws-cred }}
      - if: ${{ inputs.auth-mode == 'aws-oidc' }}
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
        with:
          aws-region: ${{ inputs.aws-region }}
          role-to-assume: ${{ inputs.aws-role }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: opentofu/setup-opentofu@592200bd4b9bbf4772ace78f887668b1aee8f716 # v1
        with:
          tofu_version_file: .opentofu-version

      - uses: gmo-media/tofu-actions/plan@v2
        with:
          dir: ${{ inputs.dir }}
